# Generated by Django 3.1.2 on 2021-12-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ver0', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coneference',
            new_name='Conference',
        ),
    ]
