# Generated by Django 3.1.2 on 2022-02-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ver0', '0002_auto_20211217_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='url',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
